# Generated by Django 6.1 on 2026-08-24 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_paymentidempotency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المؤشر")),
                (
                    "current_value",
                    models.FloatField(default=0.0, verbose_name="القيمة الحالية"),
                ),
                (
                    "target_value",
                    models.FloatField(default=0.0, verbose_name="القيمة المستهدفة"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stable", "مستقر"),
                            ("improving", "يتحسن"),
                            ("declining", "يتراجع"),
                        ],
                        default="stable",
                        max_length=50,
                    ),
                ),
                (
                    "last_modified_by_agent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_modified_timestamp", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialLeak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255, verbose_name="مصدر الهدر")),
                (
                    "estimated_cost",
                    models.FloatField(default=0.0, verbose_name="التكلفة التقديرية"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "مكتشف"),
                            ("action_taken", "تم اتخاذ إجراء"),
                            ("resolved", "تم الإيقاف"),
                        ],
                        default="identified",
                        max_length=50,
                    ),
                ),
                ("action_taken", models.TextField(blank=True, null=True)),
                (
                    "last_modified_by_agent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_modified_timestamp", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_leaks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان الخطر")),
                ("description", models.TextField(verbose_name="التفاصيل")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "مرتفع"),
                            ("critical", "حرج"),
                        ],
                        default="high",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("mitigated", "تم التخفيف"),
                            ("resolved", "تم الحل"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("resolution_summary", models.TextField(blank=True, null=True)),
                (
                    "last_modified_by_agent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_modified_timestamp", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
