# Generated by Django 6.1 on 2026-08-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_decisionmetric_financialleak_riskalert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        max_length=255, verbose_name="اسم الملف / File Name"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        default="",
                        max_length=500,
                        verbose_name="مسار الملف / File Path",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="سبب الاعتماد / Justification",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الاعتماد / Approved At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم / User",
                    ),
                ),
            ],
        ),
    ]
