# Generated by Django 6.1 on 2026-08-24 21:02

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_approvedplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salesgoal",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="rating",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="salesgoal",
            constraint=models.UniqueConstraint(
                fields=("user", "month"), name="unique_user_month_goal"
            ),
        ),
    ]
